echo " __  __       _     _ _        _   _"                        
echo "|  \/  | ___ | |__ (_) | ___  | | | | ___  __ ___   ___   _ "
echo "| |\/| |/ _ \| '_ \| | |/ _ \ | |_| |/ _ \/ _\` \ \ / / | | |"
echo "| |  | | (_) | |_) | | |  __/ |  _  |  __/ (_| |\ V /| |_| |"
echo "|_|  |_|\___/|_.__/|_|_|\___| |_| |_|\___|\__,_| \_/  \__, |"
echo "                                                      |___/ "
echo "    _         _   _ _ _                 "
echo "   / \   _ __| |_(_) | | ___ _ __ _   _ "
echo "  / _ \ | '__| __| | | |/ _ \ '__| | | |"
echo " / ___ \| |  | |_| | | |  __/ |  | |_| |"
echo "/_/   \_\_|   \__|_|_|_|\___|_|   \__, |"
echo "                                  |___/ "
echo ""
echo "        Fricciolosa Red Team"
echo "        https://github.com/fricciolosa-red-team/mobile-heavy-artillery"
echo ""
echo "[*] Deploying Mobile Heavy Artillery ... "
